# Portal — Universal Modular Core
# Makefile
#
# Run ./configure first to detect libraries, or build directly
# with defaults (assumes all dependencies installed).

# Include config.mk if generated by ./configure
-include config.mk

# Defaults (overridden by config.mk if present)
CC       ?= gcc
PREFIX   ?= /usr/local
SYSCONFDIR ?= /etc/portal
HAS_SQLITE  ?= yes
HAS_PSQL    ?= yes
HAS_SSL     ?= yes
HAS_SSH     ?= yes
HAS_LUA     ?= yes
HAS_PYTHON  ?= yes
HAS_LZMA    ?= yes
HAS_ZLIB    ?= yes

SQLITE_LIBS  ?= -lsqlite3
PSQL_CFLAGS  ?= -I$(shell pg_config --includedir 2>/dev/null || echo /usr/include/postgresql)
PSQL_LIBS    ?= -lpq
SSL_LIBS     ?= -lssl -lcrypto
SSH_LIBS     ?= -lssh
LUA_CFLAGS   ?= -I/usr/include/lua5.4
LUA_LIBS     ?= -llua5.4
PYTHON_CFLAGS ?= $(shell python3-config --includes 2>/dev/null)
PYTHON_LIBS  ?= $(shell python3-config --ldflags --embed 2>/dev/null || python3-config --ldflags 2>/dev/null) -lpython3.11
LZMA_LIBS    ?= -llzma
ZLIB_LIBS    ?= -lz

CFLAGS   = -Wall -Wextra -Werror -std=c11 -D_GNU_SOURCE -Iinclude -Isrc -Ilib/libev -Ilib/sha256
LDFLAGS  = -ldl -lm -pthread -rdynamic

# Directories
SRC_DIR     = src
CORE_DIR    = src/core
LIB_DIR     = lib
MOD_DIR     = modules
TOOLS_DIR   = tools
TESTS_DIR   = tests
BUILD_DIR   = build

# Embedded libraries (third-party, relaxed warnings)
LIBEV_OBJ   = $(BUILD_DIR)/$(LIB_DIR)/libev/ev_portal.o
SHA256_OBJ  = $(BUILD_DIR)/$(LIB_DIR)/sha256/sha256.o
LIB_FLAGS   = -std=c11 -D_GNU_SOURCE -Ilib/libev -Ilib/sha256 -w

# Core sources
CORE_SRCS   = $(CORE_DIR)/core_log.c \
              $(CORE_DIR)/core_config.c \
              $(CORE_DIR)/core_hashtable.c \
              $(CORE_DIR)/core_path.c \
              $(CORE_DIR)/core_module.c \
              $(CORE_DIR)/core_message.c \
              $(CORE_DIR)/core_auth.c \
              $(CORE_DIR)/core_pubsub.c \
              $(CORE_DIR)/core_wire.c \
              $(CORE_DIR)/core_events.c \
              $(CORE_DIR)/core_store.c \
              $(CORE_DIR)/core_storage.c \
              $(CORE_DIR)/core_event.c \
              $(CORE_DIR)/core_handlers.c \
              $(CORE_DIR)/portal_instance.c

CORE_OBJS   = $(patsubst %.c,$(BUILD_DIR)/%.o,$(CORE_SRCS))
MAIN_OBJ    = $(BUILD_DIR)/$(SRC_DIR)/main.o

# Targets
PORTAL       = $(BUILD_DIR)/portal
PORTALCTL    = $(BUILD_DIR)/portalctl
MOD_CLI      = $(MOD_DIR)/mod_cli.so
MOD_NODE     = $(MOD_DIR)/mod_node.so
MOD_PSQL     = $(MOD_DIR)/mod_config_psql.so
MOD_SQLITE   = $(MOD_DIR)/mod_config_sqlite.so
MOD_WEB      = $(MOD_DIR)/mod_web.so
MOD_HELLO    = $(MOD_DIR)/mod_hello.so
MOD_SHELL    = $(MOD_DIR)/mod_shell.so
MOD_MYAPP    = $(MOD_DIR)/mod_myapp.so
MOD_CACHE    = $(MOD_DIR)/mod_cache.so
MOD_HEALTH   = $(MOD_DIR)/mod_health.so
MOD_CRON     = $(MOD_DIR)/mod_cron.so
MOD_JSON     = $(MOD_DIR)/mod_json.so
MOD_HTTPC    = $(MOD_DIR)/mod_http_client.so
MOD_SSH      = $(MOD_DIR)/mod_ssh.so
MOD_SHM      = $(MOD_DIR)/mod_shm.so
MOD_QUEUE    = $(MOD_DIR)/mod_queue.so
MOD_WS       = $(MOD_DIR)/mod_websocket.so
MOD_MQTT     = $(MOD_DIR)/mod_mqtt.so
MOD_EMAIL    = $(MOD_DIR)/mod_email.so
MOD_LOGIC    = $(MOD_DIR)/mod_logic.so
MOD_LUA      = $(MOD_DIR)/mod_logic_lua.so
MOD_PYTHON   = $(MOD_DIR)/mod_logic_python.so
MOD_LOGIC_C  = $(MOD_DIR)/mod_logic_c.so
MOD_PASCAL   = $(MOD_DIR)/mod_logic_pascal.so
MOD_WORKER   = $(MOD_DIR)/mod_worker.so
MOD_SERIAL   = $(MOD_DIR)/mod_serial.so
MOD_FILE     = $(MOD_DIR)/mod_file.so
MOD_METRICS  = $(MOD_DIR)/mod_metrics.so
MOD_AUDIT    = $(MOD_DIR)/mod_audit.so
MOD_TEMPLATE = $(MOD_DIR)/mod_template.so
MOD_PROXY    = $(MOD_DIR)/mod_proxy.so
MOD_DNS      = $(MOD_DIR)/mod_dns.so
MOD_FIREWALL = $(MOD_DIR)/mod_firewall.so
MOD_GPIO     = $(MOD_DIR)/mod_gpio.so
MOD_PROCESS  = $(MOD_DIR)/mod_process.so
MOD_KV       = $(MOD_DIR)/mod_kv.so
MOD_WEBHOOK  = $(MOD_DIR)/mod_webhook.so
MOD_SYSINFO  = $(MOD_DIR)/mod_sysinfo.so
MOD_CRYPTO   = $(MOD_DIR)/mod_crypto.so
MOD_LOG      = $(MOD_DIR)/mod_log.so
MOD_BACKUP   = $(MOD_DIR)/mod_backup.so
MOD_LDAP     = $(MOD_DIR)/mod_ldap.so
MOD_XZ       = $(MOD_DIR)/mod_xz.so
MOD_GZIP     = $(MOD_DIR)/mod_gzip.so
MOD_VALID    = $(MOD_DIR)/mod_validator.so
MOD_SCHED    = $(MOD_DIR)/mod_scheduler.so
MOD_GATEWAY  = $(MOD_DIR)/mod_api_gateway.so
MOD_ACME     = $(MOD_DIR)/mod_acme.so
MOD_ADMIN    = $(MOD_DIR)/mod_admin.so
MOD_IOT      = $(MOD_DIR)/mod_iot.so
MOD_TUNNEL   = $(MOD_DIR)/mod_tunnel.so
MOD_WATCHDOG = $(MOD_DIR)/mod_watchdog.so
TEST_PATH    = $(BUILD_DIR)/test_path
TEST_ACL     = $(BUILD_DIR)/test_acl
TEST_HT      = $(BUILD_DIR)/test_hashtable
TEST_PUBSUB  = $(BUILD_DIR)/test_pubsub
TEST_WIRE    = $(BUILD_DIR)/test_wire
TEST_EVENTS  = $(BUILD_DIR)/test_events
TEST_EVLOOP  = $(BUILD_DIR)/test_eventloop
TEST_CRYPTO  = $(BUILD_DIR)/test_crypto
TEST_VALID   = $(BUILD_DIR)/test_validator

.PHONY: all clean modules tools tests install devtest

all: $(PORTAL) modules tools

# --- Core binary ---

$(PORTAL): $(MAIN_OBJ) $(CORE_OBJS) $(LIBEV_OBJ) $(SHA256_OBJ)
	@echo "  LINK  $@"
	@$(CC) -o $@ $^ $(LDFLAGS)

# Third-party libs — relaxed warnings
$(BUILD_DIR)/$(LIB_DIR)/%.o: $(LIB_DIR)/%.c
	@mkdir -p $(dir $@)
	@echo "  CC    $< (lib)"
	@$(CC) $(LIB_FLAGS) -c -o $@ $<

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	@echo "  CC    $<"
	@$(CC) $(CFLAGS) -c -o $@ $<

# --- Modules ---

# Build module list based on detected libraries
MOD_ALL = $(MOD_CLI) $(MOD_NODE) $(MOD_HELLO) $(MOD_SHELL) $(MOD_MYAPP) $(MOD_CACHE) \
          $(MOD_HEALTH) $(MOD_CRON) $(MOD_JSON) $(MOD_SHM) $(MOD_QUEUE) \
          $(MOD_WS) $(MOD_MQTT) $(MOD_EMAIL) $(MOD_LOGIC) $(MOD_LOGIC_C) \
          $(MOD_PASCAL) $(MOD_WORKER) $(MOD_SERIAL) $(MOD_FILE) $(MOD_METRICS) \
          $(MOD_AUDIT) $(MOD_TEMPLATE) $(MOD_PROXY) $(MOD_DNS) $(MOD_FIREWALL) \
          $(MOD_GPIO) $(MOD_PROCESS) $(MOD_KV) $(MOD_WEBHOOK) $(MOD_SYSINFO) \
          $(MOD_CRYPTO) $(MOD_LOG) $(MOD_BACKUP) $(MOD_LDAP) $(MOD_VALID) \
          $(MOD_SCHED) $(MOD_GATEWAY) $(MOD_ACME) $(MOD_ADMIN) $(MOD_IOT) \
          $(MOD_TUNNEL) $(MOD_WATCHDOG)

ifeq ($(HAS_SQLITE),yes)
MOD_ALL += $(MOD_SQLITE)
endif
ifeq ($(HAS_PSQL),yes)
MOD_ALL += $(MOD_PSQL)
endif
ifeq ($(HAS_SSL),yes)
MOD_ALL += $(MOD_WEB) $(MOD_HTTPC)
endif
ifeq ($(HAS_SSH),yes)
MOD_ALL += $(MOD_SSH)
endif
ifeq ($(HAS_LUA),yes)
MOD_ALL += $(MOD_LUA)
endif
ifeq ($(HAS_PYTHON),yes)
MOD_ALL += $(MOD_PYTHON)
endif
ifeq ($(HAS_LZMA),yes)
MOD_ALL += $(MOD_XZ)
endif
ifeq ($(HAS_ZLIB),yes)
MOD_ALL += $(MOD_GZIP)
endif

modules: $(MOD_ALL)

$(MOD_CLI): $(MOD_DIR)/mod_cli/mod_cli.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_NODE): $(MOD_DIR)/mod_node/mod_node.c $(CORE_DIR)/core_message.c $(CORE_DIR)/core_wire.c $(CORE_DIR)/core_hashtable.c $(LIB_DIR)/sha256/sha256.c
	@echo "  SO    $@"
ifeq ($(HAS_SSL),yes)
	@$(CC) $(CFLAGS) -DHAS_SSL -Ilib/sha256 -pthread -shared -fPIC -o $@ $^ $(SSL_LIBS)
else
	@$(CC) $(CFLAGS) -Ilib/sha256 -pthread -shared -fPIC -o $@ $^
endif

$(MOD_PSQL): $(MOD_DIR)/mod_config_psql/mod_config_psql.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(PSQL_LIBS) $(PSQL_CFLAGS)

$(MOD_SQLITE): $(MOD_DIR)/mod_config_sqlite/mod_config_sqlite.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(SQLITE_LIBS)

$(MOD_WEB): $(MOD_DIR)/mod_web/mod_web.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(SSL_LIBS)

$(MOD_HELLO): $(MOD_DIR)/mod_hello/mod_hello.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_SHELL): $(MOD_DIR)/mod_shell/mod_shell.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_MYAPP): $(MOD_DIR)/mod_myapp/mod_myapp.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_CACHE): $(MOD_DIR)/mod_cache/mod_cache.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_HEALTH): $(MOD_DIR)/mod_health/mod_health.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_CRON): $(MOD_DIR)/mod_cron/mod_cron.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_JSON): $(MOD_DIR)/mod_json/mod_json.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_HTTPC): $(MOD_DIR)/mod_http_client/mod_http_client.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(SSL_LIBS)

$(MOD_SSH): $(MOD_DIR)/mod_ssh/mod_ssh.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^ $(SSH_LIBS)

$(MOD_SHM): $(MOD_DIR)/mod_shm/mod_shm.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ -lrt

$(MOD_QUEUE): $(MOD_DIR)/mod_queue/mod_queue.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_WS): $(MOD_DIR)/mod_websocket/mod_websocket.c $(CORE_DIR)/core_message.c $(LIB_DIR)/sha256/sha256.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^ -Ilib/sha256

$(MOD_MQTT): $(MOD_DIR)/mod_mqtt/mod_mqtt.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_EMAIL): $(MOD_DIR)/mod_email/mod_email.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_LOGIC): $(MOD_DIR)/mod_logic/mod_logic.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_LUA): $(MOD_DIR)/mod_logic_lua/mod_logic_lua.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(LUA_LIBS) $(LUA_CFLAGS)

$(MOD_LOGIC_C): $(MOD_DIR)/mod_logic_c/mod_logic_c.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ -ldl

$(MOD_PASCAL): $(MOD_DIR)/mod_logic_pascal/mod_logic_pascal.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ -ldl

$(MOD_PYTHON): $(MOD_DIR)/mod_logic_python/mod_logic_python.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(PYTHON_CFLAGS) $(PYTHON_LIBS)

$(MOD_WORKER): $(MOD_DIR)/mod_worker/mod_worker.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_SERIAL): $(MOD_DIR)/mod_serial/mod_serial.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_FILE): $(MOD_DIR)/mod_file/mod_file.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_METRICS): $(MOD_DIR)/mod_metrics/mod_metrics.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_AUDIT): $(MOD_DIR)/mod_audit/mod_audit.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_TEMPLATE): $(MOD_DIR)/mod_template/mod_template.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_PROXY): $(MOD_DIR)/mod_proxy/mod_proxy.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_DNS): $(MOD_DIR)/mod_dns/mod_dns.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_FIREWALL): $(MOD_DIR)/mod_firewall/mod_firewall.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_GPIO): $(MOD_DIR)/mod_gpio/mod_gpio.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_PROCESS): $(MOD_DIR)/mod_process/mod_process.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_KV): $(MOD_DIR)/mod_kv/mod_kv.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_WEBHOOK): $(MOD_DIR)/mod_webhook/mod_webhook.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_SYSINFO): $(MOD_DIR)/mod_sysinfo/mod_sysinfo.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_CRYPTO): $(MOD_DIR)/mod_crypto/mod_crypto.c $(CORE_DIR)/core_message.c $(LIB_DIR)/sha256/sha256.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ -Ilib/sha256

$(MOD_LOG): $(MOD_DIR)/mod_log/mod_log.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_BACKUP): $(MOD_DIR)/mod_backup/mod_backup.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_LDAP): $(MOD_DIR)/mod_ldap/mod_ldap.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_XZ): $(MOD_DIR)/mod_xz/mod_xz.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(LZMA_LIBS)

$(MOD_GZIP): $(MOD_DIR)/mod_gzip/mod_gzip.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(ZLIB_LIBS)

$(MOD_VALID): $(MOD_DIR)/mod_validator/mod_validator.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_SCHED): $(MOD_DIR)/mod_scheduler/mod_scheduler.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_GATEWAY): $(MOD_DIR)/mod_api_gateway/mod_api_gateway.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_ACME): $(MOD_DIR)/mod_acme/mod_acme.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_ADMIN): $(MOD_DIR)/mod_admin/mod_admin.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

$(MOD_IOT): $(MOD_DIR)/mod_iot/mod_iot.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^ $(SSL_LIBS)

$(MOD_TUNNEL): $(MOD_DIR)/mod_tunnel/mod_tunnel.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -pthread -shared -fPIC -o $@ $^

$(MOD_WATCHDOG): $(MOD_DIR)/mod_watchdog/mod_watchdog.c $(CORE_DIR)/core_message.c
	@echo "  SO    $@"
	@$(CC) $(CFLAGS) -shared -fPIC -o $@ $^

# --- Tools ---

tools: $(PORTALCTL)

$(PORTALCTL): $(TOOLS_DIR)/portalctl.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $<

# --- Tests ---

tests: $(TEST_PATH) $(TEST_ACL) $(TEST_HT) $(TEST_PUBSUB) $(TEST_WIRE) $(TEST_EVENTS) $(TEST_EVLOOP) $(TEST_CRYPTO) $(TEST_VALID)
	@echo ""
	@echo "Running tests..."
	@echo "================"
	@$(TEST_PATH)
	@echo ""
	@$(TEST_ACL)
	@echo ""
	@$(TEST_HT)
	@echo ""
	@$(TEST_PUBSUB)
	@echo ""
	@$(TEST_WIRE)
	@echo ""
	@$(TEST_EVENTS)
	@echo ""
	@$(TEST_EVLOOP)
	@echo ""
	@$(TEST_CRYPTO)
	@echo ""
	@$(TEST_VALID)

$(TEST_CRYPTO): $(TESTS_DIR)/test_crypto.c $(LIB_DIR)/sha256/sha256.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -Ilib/sha256 -o $@ $^

$(TEST_VALID): $(TESTS_DIR)/test_validator.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

$(TEST_EVENTS): $(TESTS_DIR)/test_events.c $(CORE_DIR)/core_events.c $(CORE_DIR)/core_message.c $(CORE_DIR)/core_log.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

$(TEST_EVLOOP): $(TESTS_DIR)/test_eventloop.c $(CORE_DIR)/core_event.c $(CORE_DIR)/core_hashtable.c $(CORE_DIR)/core_log.c $(LIBEV_OBJ)
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -Ilib/libev -o $@ $^ -lm

$(TEST_PATH): $(TESTS_DIR)/test_path.c $(CORE_DIR)/core_path.c $(CORE_DIR)/core_message.c $(CORE_DIR)/core_hashtable.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

$(TEST_ACL): $(TESTS_DIR)/test_acl.c $(CORE_DIR)/core_path.c $(CORE_DIR)/core_message.c $(CORE_DIR)/core_hashtable.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

$(TEST_HT): $(TESTS_DIR)/test_hashtable.c $(CORE_DIR)/core_hashtable.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

$(TEST_PUBSUB): $(TESTS_DIR)/test_pubsub.c $(CORE_DIR)/core_pubsub.c $(CORE_DIR)/core_log.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

$(TEST_WIRE): $(TESTS_DIR)/test_wire.c $(CORE_DIR)/core_wire.c $(CORE_DIR)/core_message.c
	@mkdir -p $(BUILD_DIR)
	@echo "  CC    $@"
	@$(CC) $(CFLAGS) -o $@ $^

# --- Clean ---

clean:
	rm -rf $(BUILD_DIR)
	rm -f $(MOD_DIR)/*.so

# --- Install ---

install: all
	install -d $(PREFIX)/bin
	install -d /usr/lib/portal/modules
	install -d /etc/portal
	install -m 755 $(PORTAL) $(PREFIX)/bin/portal
	install -m 755 $(PORTALCTL) $(PREFIX)/bin/portalctl
	install -m 644 $(MOD_CLI) /usr/lib/portal/modules/
	install -m 644 $(MOD_NODE) /usr/lib/portal/modules/
	@# Install all built modules
	@for mod in $(MOD_ALL); do \
		install -m 644 $$mod /usr/lib/portal/modules/; \
	done
	install -m 644 etc/portal.service /etc/systemd/system/portal.service
	install -m 644 etc/portal-devtest.service /etc/systemd/system/portal-devtest.service
	install -m 644 etc/portal-devtest2.service /etc/systemd/system/portal-devtest2.service
	@# Create default instance if it doesn't exist
	@test -d /etc/portal/default || $(PREFIX)/bin/portal -C default >/dev/null 2>&1 || true
	@# Update all instances with missing module configs
	@$(PREFIX)/bin/portal -U 2>/dev/null || true
	@echo ""
	@echo "Installed. 45 modules in /usr/lib/portal/modules/"
	@echo ""
	@echo "  Create instance:  portal -C <name>"
	@echo "  Delete instance:  portal -D <name>"
	@echo "  Start instance:   portal -n <name> -f -d"
	@echo "  Connect CLI:      portal -n <name> -r"
	@echo ""
	@echo "  Systemd:   systemctl enable portal-<name>"
	@echo "             systemctl start portal-<name>"

# --- Dev test instance ---

devtest: install
	@echo "Setting up devtest instance..."
	@install -d /etc/portal/devtest /etc/portal/devtest/users /etc/portal/devtest/groups /etc/portal/devtest/modules
	@test -f /etc/portal/devtest/portal.conf || cp etc/devtest.conf /etc/portal/devtest/portal.conf
	@test -f /etc/portal/devtest/users/root.conf || printf "password = portal\napi_key = auto\ngroups = root\n" > /etc/portal/devtest/users/root.conf
	@test -f /etc/portal/devtest/users/admin.conf || printf "password = admin\napi_key = auto\ngroups = admin,dev\n" > /etc/portal/devtest/users/admin.conf
	@echo ""
	@echo "Devtest instance ready. Run with:"
	@echo "  portal -n devtest -f -d"
	@echo "  portal -n devtest -r"

devtest2: install
	@echo "Setting up devtest2 instance..."
	@install -d /etc/portal/devtest2 /etc/portal/devtest2/users /etc/portal/devtest2/groups /etc/portal/devtest2/modules
	@cp etc/devtest2.conf /etc/portal/devtest2/portal.conf
	@test -f /etc/portal/devtest2/users/root.conf || printf "password = portal\napi_key = auto\ngroups = root\n" > /etc/portal/devtest2/users/root.conf
	@echo ""
	@echo "Devtest2 instance ready. Run with:"
	@echo "  portal -n devtest2 -f -d"
	@echo "  portal -n devtest2 -r"
